### ISSUE TITLE
Add support for POSIX groups and accounts

### ISSUE THREAD

**Issue by jirwin** [ConductorOne/baton-ldap#6]
Today we discover and list groups using `groupOfUniqueNames`. In addition to this, we should also be sure to discover POSIX groups and accounts.

We should be able to search for these by the objectclass: `posixGroup` and `posixAccount`. We'll want to be sure that group membership is granted to the correct user as well.

https://docs.debops.org/en/v3.0.0/ansible/roles/ldap/ldap-posix.html This may be a good resource for learning more about how posix groups and accounts are used.

**Comment by martinalbert** [comment]
@jirwin looking more into this and with `posixGroup` and `posixAccount`, there are additional attributes that might be used along these auxiliary classes such as `gidNumber` identifying group or `uidNumber` identifying user/account. Are mentioned attributes or some other required to be integrated into resources? This decision would require more changes, making the connector more robust and complex.

**Comment by jirwin** [comment]
What are the additional changes you're thinking of? I think for something like `gidNumber` or `uidNumber`, it would be good to add them to the profile on the associated user/group trait.
